[project]
name = "image_table_into_XLSL"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas",
    "camelot-py @ git+https://github.com/Mairooriam/camelot.git",
    "jupyter"
]
